# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pink Tangent
email: tangentmelb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  twitter: <a href="https://twitter.com/pink_tangent">@pink_tangent</a><br>Personal Blog: <a href="https://pinktangent.me/">PinkTangent</a><br><img src="https://pinktangent.github.io/images/pinkie.png" width="300" height="300" alt="pinktangent">
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-theme-minimal
